# Generated by Django 4.0.3 on 2022-04-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_fixed_price',
            new_name='unit_price',
        ),
    ]
